# Proposed structure for the book

-   Preface
-   Introduction
    -   What is Phenotyping
    -   The phenotyping process
    - Clinical description
-   OMOP CDM vocabularies
    - Introduction
    - Condition based concepts
    - Drug based concepts
    - Measurement based concepts
    - Observation based concepts
    - Procedures based concepts
    - Devices based concepts
-   Codes in OMOP CDM
  - Introduction
  - Codelists
  - Codelist with details
  - Concept set expression
  - get candidate codelists
  - Create a condition based codelist (example stroke)
  - Create a 
  - Create a drug based codelist (example chemotheraphy)
  - Create a drug based codelist (example )
- Create cohorts
  - Base cohorts
  - Demographic cohorts
  - Inclusion criteria
  - Set the end date
  - Combine cohorts
  - Example cohorts (obesity + causal inference centered on a complicated end date e.g. venla study)
- Phenotype validation
  - Database Feasibility
    - Introduction
    - Metadata
    - The person table
    - The observation period
    - Clinical tables
    - Record trends
  - Codelist diagnostics
    - Code use
    - Orphan codes
    - Drug exposure diagnostics
    - Measurement diagnostics
  - Cohort diagnostics
    - Counts and attrition
    - Characterisation and large scale characterisation
    - Matched comparison
    - Overlap and timing
    - Survival
  - Population diagnostics
    - Incidence
    - Prevalence
  - Study workflow and final remarks

```{r}
library(CodelistGenerator)
library(PhenotypeR)
library(omock)
library(duckdb)
```
